# Generated by Django 5.2.10 on 2026-01-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='카테고리 ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='카테고리 아이콘 URL')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ingredients.ingredientcategory', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '식재료 카테고리',
                'verbose_name_plural': '식재료 카테고리',
                'db_table': 'IngredientCategory',
            },
        ),
        migrations.CreateModel(
            name='IngredientMaster',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='식재료 ID')),
                ('name_ko', models.CharField(db_index=True, max_length=50, verbose_name='한글명')),
                ('name_en', models.CharField(blank=True, help_text='Spoonacular API 매핑용 공식 영문명', max_length=100, null=True, verbose_name='영문명')),
                ('aliases', models.JSONField(blank=True, help_text='["토마토", "tomato"] 형식', null=True, verbose_name='별칭/번역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='ingredients.ingredientcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '식재료 마스터',
                'verbose_name_plural': '식재료 마스터',
                'db_table': 'IngredientMaster',
            },
        ),
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('user_ingredient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='사용자 식재료 ID')),
                ('expire_at', models.DateField(blank=True, help_text='입력 안하면 가중치 제외', null=True, verbose_name='유통기한')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='사용 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_ingredients', to='ingredients.ingredientmaster', verbose_name='식재료')),
            ],
            options={
                'verbose_name': '사용자 식재료',
                'verbose_name_plural': '사용자 식재료',
                'db_table': 'UserIngredient',
            },
        ),
    ]
