# Generated by Django 5.2.10 on 2026-02-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='ingredientcategory',
            index=models.Index(fields=['parent'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='ingredientmaster',
            index=models.Index(fields=['category'], name='idx_ingredient_category'),
        ),
        migrations.AddIndex(
            model_name='ingredientmaster',
            index=models.Index(fields=['name_ko'], name='idx_ingredient_name'),
        ),
        migrations.AddIndex(
            model_name='ingredientmaster',
            index=models.Index(fields=['name_en'], name='idx_ingredient_name_en'),
        ),
        migrations.AddIndex(
            model_name='ingredientnamemapping',
            index=models.Index(fields=['alternative_name'], name='idx_mapping_alt_name'),
        ),
        migrations.AddIndex(
            model_name='ingredientnamemapping',
            index=models.Index(fields=['source'], name='idx_mapping_source'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientnamemapping',
            unique_together={('ingredient', 'alternative_name')},
        ),
        migrations.AddIndex(
            model_name='useringredient',
            index=models.Index(fields=['user'], name='idx_user_ingredient_user'),
        ),
        migrations.AddIndex(
            model_name='useringredient',
            index=models.Index(fields=['ingredient'], name='idx_user_ingredient_ing'),
        ),
        migrations.AddIndex(
            model_name='useringredient',
            index=models.Index(fields=['expire_at'], name='idx_user_ingredient_expire'),
        ),
        migrations.AddIndex(
            model_name='useringredient',
            index=models.Index(fields=['user', 'is_consumed'], name='idx_user_ingredient_active'),
        ),
    ]
