"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# .env 파일 내용을 불러옵니다.
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-v_eb4#s#zw_i1jk*d7&_kcp+(b8m)tv(x(fz98g5juxlb21r8p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',  # API 문서 자동 생성
    'django_filters',
    'ingredients',
    'recipes',
    'logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 기존 sqlite3 설정은 지우고 아래 내용으로 교체!
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # postgresql 엔진 사용
        'NAME': os.getenv('DB_NAME', 'recipick_db'),# pgAdmin에서 만든 DB 이름
        'USER': os.getenv('DB_USER', 'postgres'),   # 설치 시 기본 ID
        'PASSWORD': os.getenv('DB_PASSWORD'),       # .env 파일에서 비밀번호 가져오기
        'HOST': os.getenv('DB_HOST', 'localhost'),  # 내 컴퓨터
        'PORT': os.getenv('DB_PORT', '5432'),       # 기본 포트
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 정적 파일 (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 기본 django 모델 말고 직접 만든 유저 모델 사용
AUTH_USER_MODEL = 'users.User'

# logs/models.py의 이미지 관련
# 1. 브라우저에서 접근할 때 쓸 URL 주소 (예: http://localhost:8000/media/...)
MEDIA_URL = '/media/'
# 2. 실제로 파일이 저장될 컴퓨터 내의 경로 (프로젝트 폴더 내 'media' 폴더)
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Spoonacular API (환경변수로 관리)
SPOONACULAR_API_KEY = os.getenv('SPOONACULAR_API_KEY', '')

# ==================== REST Framework 설정 ==================== #
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# JWT 설정 (SimpleJWT)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'user_id',
}

# CORS 설정 (프론트엔드와 통신)
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://localhost:5173'
).split(',')

CORS_ALLOW_CREDENTIALS = True

# ==================== Spoonacular API 키 확인 ==================== #
if not SPOONACULAR_API_KEY:
    print("⚠️  WARNING: SPOONACULAR_API_KEY가 설정되지 않았습니다!")
    print("   .env 파일에 SPOONACULAR_API_KEY를 추가해주세요.")
else:
    print(f"✅ Spoonacular API Key 로드 완료: {SPOONACULAR_API_KEY[:10]}...")

# ▼ 개발 단계에서 static 폴더 위치 지정 (이게 있어야 static 폴더 인식함)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]