# Generated by Django 5.2.10 on 2026-01-28 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('favorite_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='찜 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='찜한 시점')),
            ],
            options={
                'verbose_name': '찜한 레시피',
                'verbose_name_plural': '찜한 레시피',
                'db_table': 'FavoriteRecipe',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='레시피 ID')),
                ('external_id', models.CharField(blank=True, help_text='Spoonacular ID 등', max_length=255, null=True, verbose_name='외부 API ID')),
                ('source', models.CharField(choices=[('spoonacular', 'Spoonacular'), ('korean_food', '한식 DB'), ('user_created', '사용자 생성'), ('other', '기타')], max_length=50, verbose_name='출처')),
                ('title', models.CharField(max_length=200, verbose_name='레시피 제목')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='썸네일 이미지')),
                ('ready_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='예상 조리시간(분)')),
                ('difficulty', models.CharField(choices=[('EASY', '쉬움'), ('NORMAL', '보통'), ('DIFFICULT', '어려움')], default='NORMAL', max_length=20, verbose_name='난이도')),
                ('servings', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='인분')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='API 원본 데이터')),
                ('instructions', models.JSONField(blank=True, help_text='[{"step": 1, "description": "..."}, ...] 형식', null=True, verbose_name='조리 단계')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='캐싱/등록 시점')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('total_ingredients', models.IntegerField(default=0, help_text='RecipeIngredient 저장 시 자동 업데이트', verbose_name='전체 재료 수')),
                ('required_ingredients', models.IntegerField(default=0, help_text='선택 재료 제외한 필수 재료 수', verbose_name='필수 재료 수')),
                ('is_active', models.BooleanField(default=True, help_text='추천 목록에 표시 여부', verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피',
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('recipe_ingredient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='레시피 식재료 ID')),
                ('ingredient_name', models.CharField(help_text='원본 API에서 사용하는 이름', max_length=100, verbose_name='식재료명(API 기준)')),
                ('is_optional', models.BooleanField(default=False, verbose_name='선택 재료 여부')),
            ],
            options={
                'verbose_name': '레시피 식재료',
                'verbose_name_plural': '레시피 식재료',
                'db_table': 'RecipeIngredient',
            },
        ),
    ]
