# Generated by Django 5.2.10 on 2026-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLog',
            fields=[
                ('recipe_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cooked_at', models.DateField()),
                ('rating', models.IntegerField()),
                ('perceived_difficulty', models.CharField(choices=[('EASY', '쉬움'), ('NORMAL', '보통'), ('DIFFICULT', '어려움')], max_length=20)),
                ('memo', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_logs/original/%Y/%m/%d/')),
                ('shared_image', models.ImageField(blank=True, null=True, upload_to='recipe_logs/shared/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'RecipeLog',
            },
        ),
    ]
